[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Alice Zhen <lishi.alice@hotmail.fr>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
